// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxlmwcuohqisfhycpsoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bG13Y3VvaHFpc2ZoeWNwc29hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODM2ODUsImV4cCI6MjA3MTQ1OTY4NX0.f01Zgn8c2aiUriOH0OTUeUC3IauyMYhQ2bWY3CYzyqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});